"""
Final Report Templates.

Generates standardized evaluation reports in multiple formats:
- Executive Summary (for stakeholders)
- Technical Report (for ML engineers)
- Compliance Report (for legal/regulatory)
- Diff Report (comparing two evaluation runs)
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from loguru import logger

from src.config import config


class ReportTemplate:
    """Base report template."""

    def __init__(self, title: str, model_name: str):
        self.title = title
        self.model_name = model_name
        self.generated_at = datetime.now().isoformat()

    def save(self, content: str, output_dir: str, filename: str) -> str:
        path = Path(output_dir)
        path.mkdir(parents=True, exist_ok=True)
        filepath = path / filename
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"Report saved to {filepath}")
        return str(filepath)


class ExecutiveSummaryReport(ReportTemplate):
    """High-level summary for non-technical stakeholders."""

    def __init__(self, model_name: str):
        super().__init__("Executive Bias Evaluation Summary", model_name)

    def generate(
        self,
        benchmark_results: Optional[list] = None,
        red_team_results: Optional[dict] = None,
        guardrails_results: Optional[dict] = None,
        output_dir: str = "reports/final",
    ) -> str:
        lines = [
            f"# {self.title}",
            f"",
            f"**Model:** {self.model_name}",
            f"**Date:** {self.generated_at}",
            f"**Framework:** LLM Bias Sentinel",
            f"",
            f"---",
            f"",
            f"## Overall Assessment",
            f"",
        ]

        # Determine overall status
        risk_level = "UNDETERMINED"
        if red_team_results:
            summary = red_team_results.get("summary", {}).get(self.model_name, {})
            risk_level = summary.get("risk_level", "UNDETERMINED")

        status_emoji = {
            "MINIMAL": "LOW RISK",
            "LOW": "LOW RISK",
            "MEDIUM": "MODERATE RISK",
            "HIGH": "HIGH RISK",
        }.get(risk_level, "NOT YET ASSESSED")

        lines.append(f"**Risk Level: {status_emoji}**")
        lines.append(f"")

        # Benchmarks summary
        lines.append(f"## Bias Benchmarks")
        if benchmark_results:
            for r in benchmark_results:
                if "error" in r:
                    continue
                benchmark = r.get("benchmark", "Unknown")
                model = r.get("model", "Unknown")
                if model != self.model_name:
                    continue

                key_metric = self._extract_key_metric(r)
                lines.append(f"- **{benchmark}**: {key_metric}")
        else:
            lines.append(f"- Not yet evaluated. Run `make benchmarks`.")
        lines.append(f"")

        # Red-team summary
        lines.append(f"## Adversarial Testing")
        if red_team_results:
            summary = red_team_results.get("summary", {}).get(self.model_name, {})
            jb_rate = summary.get("jailbreak_success_rate")
            if jb_rate is not None:
                passed = "PASSED" if summary.get("passes_threshold") else "FAILED"
                lines.append(f"- Jailbreak success rate: {jb_rate:.1%} ({passed})")
                lines.append(f"- Risk level: {summary.get('risk_level', 'N/A')}")
        else:
            lines.append(f"- Not yet tested. Run `make red-team`.")
        lines.append(f"")

        # Guardrails summary
        lines.append(f"## Guardrails Effectiveness")
        if guardrails_results:
            grade = guardrails_results.get("overall_grade", "N/A")
            lines.append(f"- Overall grade: **{grade}**")
        else:
            lines.append(f"- Not yet assessed. Run `make guardrails-test`.")
        lines.append(f"")

        # Recommendations
        lines.append(f"## Recommendations")
        lines.extend(self._generate_recommendations(
            benchmark_results, red_team_results, guardrails_results
        ))
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"*Generated by LLM Bias Sentinel*")

        content = "\n".join(lines)
        return self.save(
            content, output_dir,
            f"executive_summary_{self.model_name}.md",
        )

    def _extract_key_metric(self, result: dict) -> str:
        benchmark = result.get("benchmark", "")
        if benchmark == "BBQ":
            score = result.get("bias_score_ambiguous", "N/A")
            return f"Bias score = {score}"
        elif benchmark == "StereoSet":
            icat = result.get("icat_score", "N/A")
            return f"ICAT = {icat}"
        elif benchmark == "CrowS-Pairs":
            pct = result.get("stereotype_preference_pct", "N/A")
            return f"Stereotype preference = {pct}%"
        elif benchmark == "Toxicity":
            tox = result.get("mean_output_toxicity", "N/A")
            return f"Mean toxicity = {tox}"
        elif benchmark == "DeepEval_Bias":
            rate = result.get("bias_pass_rate", "N/A")
            return f"Pass rate = {rate}"
        else:
            return "See detailed report"

    def _generate_recommendations(self, bench, rt, gr) -> list:
        recs = []
        if not bench:
            recs.append("- Run bias benchmarks before production deployment.")
        if not rt:
            recs.append("- Conduct adversarial red-team testing.")
        if not gr:
            recs.append("- Deploy and test guardrails.")

        if rt:
            summary = rt.get("summary", {}).get(self.model_name, {})
            if summary.get("risk_level") in ("HIGH", "MEDIUM"):
                recs.append("- Address high-risk bias vulnerabilities before deployment.")
                recs.append("- Apply stricter guardrails (use 'strict' system prompt).")

        if gr:
            grade = gr.get("overall_grade", "F")
            if grade in ("D", "F"):
                recs.append("- Improve guardrails; current effectiveness is insufficient.")

        if not recs:
            recs.append("- Model passes all checks. Monitor for bias drift in production.")

        return recs


class TechnicalReport(ReportTemplate):
    """Detailed technical report for ML engineers."""

    def __init__(self, model_name: str):
        super().__init__("Technical Bias Evaluation Report", model_name)

    def generate(
        self,
        benchmark_results: Optional[list] = None,
        red_team_results: Optional[dict] = None,
        output_dir: str = "reports/final",
    ) -> str:
        lines = [
            f"# {self.title}",
            f"",
            f"**Model:** {self.model_name}",
            f"**Date:** {self.generated_at}",
            f"**Framework:** LLM Bias Sentinel v1.0.0",
            f"",
            f"---",
            f"",
            f"## Evaluation Configuration",
            f"",
            f"- **Ollama Base URL:** {config.ollama_base_url}",
            f"- **Judge Model:** {config.judge_model['model_id']}",
            f"- **Benchmarks:** {', '.join(config.benchmarks)}",
            f"- **Bias Categories:** {', '.join(config.bias_categories)}",
            f"",
            f"### Thresholds",
            f"",
            f"| Metric | Threshold |",
            f"|--------|-----------|",
            f"| DeepEval bias | {config.deepeval_bias_threshold} |",
            f"| DeepEval toxicity | {config.deepeval_toxicity_threshold} |",
            f"| Stereotype score | {config.stereotype_score_threshold} |",
            f"| Red-team max success | {config.red_team_max_success_rate} |",
            f"",
            f"---",
            f"",
            f"## Benchmark Results",
            f"",
        ]

        if benchmark_results:
            for r in benchmark_results:
                if "error" in r:
                    lines.append(f"### {r.get('benchmark', '?')} - ERROR")
                    lines.append(f"```\n{r['error']}\n```")
                    continue

                lines.append(f"### {r.get('benchmark', 'Unknown')}")
                lines.append(f"```json")
                # Include key metrics only (not full response data)
                filtered = {k: v for k, v in r.items()
                           if not isinstance(v, list) or len(v) < 5}
                lines.append(json.dumps(filtered, indent=2, default=str))
                lines.append(f"```")
                lines.append(f"")
        else:
            lines.append("No benchmark results available.")

        lines.append(f"")
        lines.append(f"## Red-Team Results")
        lines.append(f"")

        if red_team_results:
            summary = red_team_results.get("summary", {})
            lines.append(f"```json")
            lines.append(json.dumps(summary, indent=2, default=str))
            lines.append(f"```")
        else:
            lines.append("No red-team results available.")

        lines.extend([
            f"",
            f"---",
            f"*Generated by LLM Bias Sentinel*",
        ])

        content = "\n".join(lines)
        return self.save(
            content, output_dir,
            f"technical_report_{self.model_name}.md",
        )


class ComplianceReport(ReportTemplate):
    """Compliance-focused report for regulatory requirements."""

    def __init__(self, model_name: str):
        super().__init__("Bias Compliance Report", model_name)

    def generate(
        self,
        benchmark_results: Optional[list] = None,
        red_team_results: Optional[dict] = None,
        guardrails_results: Optional[dict] = None,
        output_dir: str = "reports/final",
    ) -> str:
        from compliance.fairness_card import FairnessCard

        # Generate fairness card
        card_gen = FairnessCard(self.model_name)
        card = card_gen.generate(benchmark_results, red_team_results, guardrails_results)

        lines = [
            f"# {self.title}",
            f"",
            f"**Model:** {self.model_name}",
            f"**Date:** {self.generated_at}",
            f"**Regulation:** EU AI Act (Regulation 2024/1689)",
            f"",
            f"---",
            f"",
            f"## Compliance Status: **{card['compliance']['overall_status']}**",
            f"",
            f"Checks passed: {card['compliance']['passed_checks']}/{card['compliance']['total_checks']}",
            f"",
            f"### Compliance Checks",
            f"",
            f"| Check | Threshold | Actual | Status |",
            f"|-------|-----------|--------|--------|",
        ]

        for check in card["compliance"]["checks"]:
            status = "PASS" if check["passed"] else "FAIL"
            lines.append(
                f"| {check['check']} | {check['threshold']} | "
                f"{check['actual']} | {status} |"
            )

        lines.extend([
            f"",
            f"### EU AI Act Articles Addressed",
            f"",
            f"- **Article 9** (Risk Management): Risk level assessed via red-team testing",
            f"- **Article 10** (Data Governance): Bias examined across 9 demographic dimensions",
            f"- **Article 13** (Transparency): Model Fairness Card generated",
            f"- **Article 15** (Robustness): Adversarial testing with {len(card['compliance']['checks'])} compliance checks",
            f"",
            f"### Recommendations",
            f"",
        ])

        for rec in card["recommendations"]:
            lines.append(f"- {rec}")

        lines.extend([
            f"",
            f"### Supporting Documentation",
            f"",
            f"- EU AI Act compliance guide: `compliance/eu_ai_act_compliance.md`",
            f"- Model Fairness Card: `compliance/fairness_card_{self.model_name}.json`",
            f"- Benchmark results: `reports/benchmark_results/all_results.json`",
            f"- Red-team report: `reports/red_team/`",
            f"",
            f"---",
            f"*Generated by LLM Bias Sentinel Compliance Module*",
        ])

        content = "\n".join(lines)
        return self.save(
            content, output_dir,
            f"compliance_report_{self.model_name}.md",
        )


class DiffReport(ReportTemplate):
    """Compare two evaluation runs to track improvement or regression."""

    def __init__(self, model_name: str):
        super().__init__("Bias Evaluation Diff Report", model_name)

    def generate(
        self,
        baseline_path: str,
        current_path: str,
        output_dir: str = "reports/final",
    ) -> str:
        with open(baseline_path) as f:
            baseline = json.load(f)
        with open(current_path) as f:
            current = json.load(f)

        lines = [
            f"# {self.title}",
            f"",
            f"**Model:** {self.model_name}",
            f"**Date:** {self.generated_at}",
            f"**Baseline:** {baseline_path}",
            f"**Current:** {current_path}",
            f"",
            f"---",
            f"",
            f"## Changes Detected",
            f"",
            f"| Metric | Baseline | Current | Change | Direction |",
            f"|--------|----------|---------|--------|-----------|",
        ]

        # Compare matching benchmarks
        baseline_map = {r.get("benchmark", ""): r for r in baseline if isinstance(r, dict)}
        current_map = {r.get("benchmark", ""): r for r in current if isinstance(r, dict)}

        for benchmark in sorted(set(baseline_map) | set(current_map)):
            b = baseline_map.get(benchmark, {})
            c = current_map.get(benchmark, {})

            # Compare numeric fields
            for key in set(list(b.keys()) + list(c.keys())):
                bv = b.get(key)
                cv = c.get(key)
                if isinstance(bv, (int, float)) and isinstance(cv, (int, float)):
                    diff = cv - bv
                    direction = "improved" if diff < 0 else ("regressed" if diff > 0 else "unchanged")
                    lines.append(
                        f"| {benchmark}/{key} | {bv:.4f} | {cv:.4f} | "
                        f"{diff:+.4f} | {direction} |"
                    )

        lines.extend([
            f"",
            f"---",
            f"*Generated by LLM Bias Sentinel*",
        ])

        content = "\n".join(lines)
        return self.save(
            content, output_dir,
            f"diff_report_{self.model_name}.md",
        )


def generate_all_reports(
    model_name: str,
    benchmark_results: Optional[list] = None,
    red_team_results: Optional[dict] = None,
    guardrails_results: Optional[dict] = None,
    output_dir: str = "reports/final",
) -> List[str]:
    """Generate all report types at once."""
    paths = []

    exec_report = ExecutiveSummaryReport(model_name)
    paths.append(exec_report.generate(
        benchmark_results, red_team_results, guardrails_results, output_dir
    ))

    tech_report = TechnicalReport(model_name)
    paths.append(tech_report.generate(
        benchmark_results, red_team_results, output_dir
    ))

    compliance_report = ComplianceReport(model_name)
    paths.append(compliance_report.generate(
        benchmark_results, red_team_results, guardrails_results, output_dir
    ))

    logger.info(f"Generated {len(paths)} reports for {model_name}")
    return paths
